In [1]:
import numpy as np
import numpy.random as rand
import math

In [11]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [12]:
np.random.seed = 42
b = np.random.randint(2, 6, 5)
b

array([4, 4, 2, 4, 3], dtype=int32)

In [13]:
print('скалярное произведение', a @ b,'or',np.dot(a, b))
print('sum', a + b)
print('mean_sum', np.mean(a) + np.mean(b))
print(a.reshape(5,1) * b) #костыльно, но сработало)

скалярное произведение 49 or 49
sum [5 6 5 8 8]
mean_sum 6.4
[[ 4  4  2  4  3]
 [ 8  8  4  8  6]
 [12 12  6 12  9]
 [16 16  8 16 12]
 [20 20 10 20 15]]


In [14]:
#dispersion try

arr = np.random.randint(50,1000, 50)

def dispersion(arr):
    mean = np.mean(arr)
    n = np.size(arr)
    sum_ = 0
    for i in range(n):
        x = arr[i] - mean
        sum_ += x**2
    sigma = math.sqrt(sum_/n)
    return sigma
print(dispersion(arr),'\n',arr)


np.std(arr)

284.1495528766498 
 [888 698 366 684  89 491 184 916  56 771 677 949 669  64 838 969 726 385
 646 390 655 658 314 507 998 624 390 341  83 374 902 178 720 931  93 527
 690 173 992 764 879 554 205 544 279 991 284 727 557 337]


np.float64(284.1495528766498)

In [15]:
mask = arr > 150
res = arr[mask]
print(res, '\n', 'количество эл-ов удовл усл', np.size(res))

[888 698 366 684 491 184 916 771 677 949 669 838 969 726 385 646 390 655
 658 314 507 998 624 390 341 374 902 178 720 931 527 690 173 992 764 879
 554 205 544 279 991 284 727 557 337] 
 количество эл-ов удовл усл 45


In [21]:
#mse
n = 50
def mse(n):
    y_true = np.random.randint(50,1000, 50)
    y_pred = np.random.randint(5,993, 50)
    sum = 0
    #нужно нормировать перед вычислением
    norm_y_true = (y_true - np.min(y_true)) / (np.max(y_true) - np.min(y_true))
    norm_y_pred = (y_pred - np.min(y_pred)) / (np.max(y_pred) - np.min(y_pred))
    for i in range(n):
        a = (norm_y_true[i] - norm_y_pred[i])**2
        sum += a
    res = sum / n
    return res
print('псевдо мсе:',mse(n), '\n', 'rmse:', math.sqrt(mse(n)))
def mse_without_loop(n):
    y_true = np.random.randint(50,1000, 50)
    y_pred = np.random.randint(5,993, 50)
    norm_y_true = (y_true - np.min(y_true)) / (np.max(y_true) - np.min(y_true))
    norm_y_pred = (y_pred - np.min(y_pred)) / (np.max(y_pred) - np.min(y_pred))
    return np.mean((norm_y_true - norm_y_pred)**2)
print(mse_without_loop(n))

#отличаются из- за разщных массивов,
#массивы генерируются локально в функциях

псевдо мсе: 0.1930734261316853 
 rmse: 0.4624578837380827
0.212979854972021


In [47]:
print(a[1:3])
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(matrix)
matrix.T
norma = np.linalg.norm(matrix)
matrix_norm = matrix / norma
print(matrix_norm)
print(np.linalg.det(matrix_norm))
print(np.trace(matrix))

[2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0.05923489 0.11846978 0.17770466]
 [0.23693955 0.29617444 0.35540933]
 [0.41464421 0.4738791  0.53311399]]
1.1686558153948974e-18
15


In [22]:
#ну вроде попрактиковался с нампай <3

In [13]:
a = np.array([1, 2, 3])
print(a)
print(a.shape)
print(a.dtype)
b = a.reshape(3,1)
a.dtype = float
print(a.dtype)
print(b)

[1 2 3]
(3,)
int64
float64
[[1]
 [2]
 [3]]
