In [40]:
import numpy as np
import numpy.random as rand
import math

In [2]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [29]:
np.random.seed = 42
b = np.random.randint(2, 6, 5)
b

array([3, 4, 4, 5, 3], dtype=int32)

In [122]:
print('скалярное произведение', a @ b,'or',np.dot(a, b))
print('sum', a + b)
print('mean_sum', np.mean(a) + np.mean(b))
print(a.reshape(5,1) * b) #костыльно, но сработало)

скалярное произведение 58 or 58
sum [4 6 7 9 8]
mean_sum 6.8
[[ 3  4  4  5  3]
 [ 6  8  8 10  6]
 [ 9 12 12 15  9]
 [12 16 16 20 12]
 [15 20 20 25 15]]


In [73]:
#dispersion try

arr = np.random.randint(50,1000, 50)

def dispersion(arr):
    mean = np.mean(arr)
    n = np.size(arr)
    sum_ = 0
    for i in range(n):
        x = arr[i] - mean
        sum_ += x**2
    sigma = math.sqrt(sum_/n)
    return sigma
print(dispersion(arr),'\n',arr)


np.std(arr)

265.623041169248 
 [367 652 412 174 147 272 122 490 640 300 800 851 170 823 985 182 874  77
 575 455 444 633 493 861 662 587 384 575 581 816 340 875 535 356 282 970
 938 218 107 332 941 619 428 649 111 274 655 437 734  95]


np.float64(265.623041169248)

In [91]:
mask = arr > 150
res = arr[mask]
print(res, '\n', 'количество эл-ов удовл усл', np.size(res))

[367 652 412 174 272 490 640 300 800 851 170 823 985 182 874 575 455 444
 633 493 861 662 587 384 575 581 816 340 875 535 356 282 970 938 218 332
 941 619 428 649 274 655 437 734] 
 количество эл-ов удовл усл 44


In [106]:
#mse
n = 50
def mse(n):
    y_true = np.random.randint(50,1000, 50)
    y_pred = np.random.randint(5,993, 50)
    sum = 0
    #нужно нормировать перед вычислением
    norm_y_true = (y_true - np.min(y_true)) / (np.max(y_true) - np.min(y_true))
    norm_y_pred = (y_pred - np.min(y_pred)) / (np.max(y_pred) - np.min(y_pred))
    for i in range(n):
        a = (norm_y_true[i] - norm_y_pred[i])**2
        sum += a
    res = sum / n
    return res
print('псевдо мсе:',mse(n), '\n', 'rmse:', math.sqrt(mse(n)))
        


псевдо мсе: 0.1715845464946675 
 rmse: 0.4493502177406798


In [107]:
#ну вроде попрактиковался с нампай <3

SyntaxError: invalid syntax (3488445477.py, line 1)